### Numpy basics

In [1]:
import numpy as np

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [13]:
m = np.arange(12).reshape((3,4))
print(m)
print('The matrix has %d rows and %d columns '% (m.shape[0], m.shape[1]))
print('Means over columns \n', m.mean(0))
print('Means over rows \n', m.mean(1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The matrix has 3 rows and 4 columns 
Means over columns 
 [4. 5. 6. 7.]
Means over rows 
 [1.5 5.5 9.5]


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [45]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

#
outer_prod1=np.outer(u,v)
print('*The outer product u^v gives the vector: \n %s'% outer_prod1)

##
outer_prod2=np.ones((len(u),len(v)))
for i in np.arange(len(u)):
    for j in np.arange(len(v)):
        outer_prod2[i,j]=u[i]*v[j]
print('**The outer product u^v gives the vector: \n %s'% outer_prod2)

###
v = np.resize(v, (4,4))
u = np.resize(u, (4,4)).transpose()
print('***The outer product u^v gives the vector: \n %s'% (u*v))

(4,)
*The outer product u^v gives the vector: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
**The outer product u^v gives the vector: 
 [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
***The outer product u^v gives the vector: 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [60]:
import numpy.random as npr
matrix=npr.random((10,6))
matrix[matrix<0.1]=0
print(matrix)

[[0.14342305 0.         0.         0.         0.45858381 0.11334192]
 [0.         0.75486148 0.39485048 0.7469385  0.45240483 0.45008675]
 [0.47807251 0.47400393 0.80316334 0.40239252 0.90468616 0.        ]
 [0.77387434 0.12564138 0.61851357 0.         0.53862728 0.        ]
 [0.95119379 0.90540203 0.79596694 0.91527432 0.14555823 0.15773007]
 [0.18763167 0.6224959  0.9058095  0.98995518 0.71112246 0.73180041]
 [0.9092932  0.40087373 0.24985068 0.17343017 0.11945705 0.81261059]
 [0.14679237 0.26429748 0.81908918 0.31058725 0.98241745 0.2666387 ]
 [0.53365334 0.31446701 0.91077283 0.36655664 0.43359233 0.51229269]
 [0.93888648 0.         0.71687866 0.89101895 0.         0.52205125]]


4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.